// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: car.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CarRentalData {

  /// <summary>Holder for reflection information generated from car.proto</summary>
  public static partial class CarReflection {

    #region Descriptor
    /// <summary>File descriptor for car.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CarReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgljYXIucHJvdG8SBXByb3RvGh5nb29nbGUvcHJvdG9idWYvd3JhcHBlcnMu",
            "cHJvdG8aG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90byLbAQoLQ2FyUHJv",
            "dG9PYmoSCgoCaWQYASABKAUSDQoFYnJhbmQYAiABKAkSDQoFbW9kZWwYAyAB",
            "KAkSEAoIYm9keVR5cGUYBCABKAkSEgoKaG9yc2VQb3dlchgFIAEoBRIQCghm",
            "dWVsVHlwZRgGIAEoCRIPCgdnZWFyYm94GAcgASgJEg0KBWNvbG9yGAggASgJ",
            "EhMKC2Rlc2NyaXB0aW9uGAkgASgJEhMKC3ByaWNlUGVyRGF5GAogASgFEiAK",
            "BnN0YXR1cxgLIAEoDjIQLnByb3RvLkNhclN0YXR1cyo5CglDYXJTdGF0dXMS",
            "DQoJQVZBSUxBQkxFEAASDAoIUkVTRVJWRUQQARIPCgtVTkFWQUlMQUJMRRAC",
            "MkgKD0NhclByb3RvU2VydmljZRI1CglDcmVhdGVDYXISEi5wcm90by5DYXJQ",
            "cm90b09iahoSLnByb3RvLkNhclByb3RvT2JqIgBCEKoCDUNhclJlbnRhbERh",
            "dGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CarRentalData.CarStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CarRentalData.CarProtoObj), global::CarRentalData.CarProtoObj.Parser, new[]{ "Id", "Brand", "Model", "BodyType", "HorsePower", "FuelType", "Gearbox", "Color", "Description", "PricePerDay", "Status" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CarStatus {
    [pbr::OriginalName("AVAILABLE")] Available = 0,
    [pbr::OriginalName("RESERVED")] Reserved = 1,
    [pbr::OriginalName("UNAVAILABLE")] Unavailable = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CarProtoObj : pb::IMessage<CarProtoObj>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CarProtoObj> _parser = new pb::MessageParser<CarProtoObj>(() => new CarProtoObj());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CarProtoObj> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CarRentalData.CarReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CarProtoObj() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CarProtoObj(CarProtoObj other) : this() {
      id_ = other.id_;
      brand_ = other.brand_;
      model_ = other.model_;
      bodyType_ = other.bodyType_;
      horsePower_ = other.horsePower_;
      fuelType_ = other.fuelType_;
      gearbox_ = other.gearbox_;
      color_ = other.color_;
      description_ = other.description_;
      pricePerDay_ = other.pricePerDay_;
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CarProtoObj Clone() {
      return new CarProtoObj(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "brand" field.</summary>
    public const int BrandFieldNumber = 2;
    private string brand_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Brand {
      get { return brand_; }
      set {
        brand_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 3;
    private string model_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Model {
      get { return model_; }
      set {
        model_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bodyType" field.</summary>
    public const int BodyTypeFieldNumber = 4;
    private string bodyType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BodyType {
      get { return bodyType_; }
      set {
        bodyType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "horsePower" field.</summary>
    public const int HorsePowerFieldNumber = 5;
    private int horsePower_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HorsePower {
      get { return horsePower_; }
      set {
        horsePower_ = value;
      }
    }

    /// <summary>Field number for the "fuelType" field.</summary>
    public const int FuelTypeFieldNumber = 6;
    private string fuelType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FuelType {
      get { return fuelType_; }
      set {
        fuelType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gearbox" field.</summary>
    public const int GearboxFieldNumber = 7;
    private string gearbox_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Gearbox {
      get { return gearbox_; }
      set {
        gearbox_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 8;
    private string color_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Color {
      get { return color_; }
      set {
        color_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 9;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pricePerDay" field.</summary>
    public const int PricePerDayFieldNumber = 10;
    private int pricePerDay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PricePerDay {
      get { return pricePerDay_; }
      set {
        pricePerDay_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 11;
    private global::CarRentalData.CarStatus status_ = global::CarRentalData.CarStatus.Available;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CarRentalData.CarStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CarProtoObj);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CarProtoObj other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Brand != other.Brand) return false;
      if (Model != other.Model) return false;
      if (BodyType != other.BodyType) return false;
      if (HorsePower != other.HorsePower) return false;
      if (FuelType != other.FuelType) return false;
      if (Gearbox != other.Gearbox) return false;
      if (Color != other.Color) return false;
      if (Description != other.Description) return false;
      if (PricePerDay != other.PricePerDay) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Brand.Length != 0) hash ^= Brand.GetHashCode();
      if (Model.Length != 0) hash ^= Model.GetHashCode();
      if (BodyType.Length != 0) hash ^= BodyType.GetHashCode();
      if (HorsePower != 0) hash ^= HorsePower.GetHashCode();
      if (FuelType.Length != 0) hash ^= FuelType.GetHashCode();
      if (Gearbox.Length != 0) hash ^= Gearbox.GetHashCode();
      if (Color.Length != 0) hash ^= Color.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (PricePerDay != 0) hash ^= PricePerDay.GetHashCode();
      if (Status != global::CarRentalData.CarStatus.Available) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Brand.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Brand);
      }
      if (Model.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Model);
      }
      if (BodyType.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(BodyType);
      }
      if (HorsePower != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(HorsePower);
      }
      if (FuelType.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FuelType);
      }
      if (Gearbox.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Gearbox);
      }
      if (Color.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Color);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Description);
      }
      if (PricePerDay != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(PricePerDay);
      }
      if (Status != global::CarRentalData.CarStatus.Available) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Brand.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Brand);
      }
      if (Model.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Model);
      }
      if (BodyType.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(BodyType);
      }
      if (HorsePower != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(HorsePower);
      }
      if (FuelType.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FuelType);
      }
      if (Gearbox.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Gearbox);
      }
      if (Color.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Color);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Description);
      }
      if (PricePerDay != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(PricePerDay);
      }
      if (Status != global::CarRentalData.CarStatus.Available) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Brand.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Brand);
      }
      if (Model.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Model);
      }
      if (BodyType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BodyType);
      }
      if (HorsePower != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HorsePower);
      }
      if (FuelType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FuelType);
      }
      if (Gearbox.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Gearbox);
      }
      if (Color.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Color);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (PricePerDay != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PricePerDay);
      }
      if (Status != global::CarRentalData.CarStatus.Available) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CarProtoObj other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Brand.Length != 0) {
        Brand = other.Brand;
      }
      if (other.Model.Length != 0) {
        Model = other.Model;
      }
      if (other.BodyType.Length != 0) {
        BodyType = other.BodyType;
      }
      if (other.HorsePower != 0) {
        HorsePower = other.HorsePower;
      }
      if (other.FuelType.Length != 0) {
        FuelType = other.FuelType;
      }
      if (other.Gearbox.Length != 0) {
        Gearbox = other.Gearbox;
      }
      if (other.Color.Length != 0) {
        Color = other.Color;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.PricePerDay != 0) {
        PricePerDay = other.PricePerDay;
      }
      if (other.Status != global::CarRentalData.CarStatus.Available) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Brand = input.ReadString();
            break;
          }
          case 26: {
            Model = input.ReadString();
            break;
          }
          case 34: {
            BodyType = input.ReadString();
            break;
          }
          case 40: {
            HorsePower = input.ReadInt32();
            break;
          }
          case 50: {
            FuelType = input.ReadString();
            break;
          }
          case 58: {
            Gearbox = input.ReadString();
            break;
          }
          case 66: {
            Color = input.ReadString();
            break;
          }
          case 74: {
            Description = input.ReadString();
            break;
          }
          case 80: {
            PricePerDay = input.ReadInt32();
            break;
          }
          case 88: {
            Status = (global::CarRentalData.CarStatus) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Brand = input.ReadString();
            break;
          }
          case 26: {
            Model = input.ReadString();
            break;
          }
          case 34: {
            BodyType = input.ReadString();
            break;
          }
          case 40: {
            HorsePower = input.ReadInt32();
            break;
          }
          case 50: {
            FuelType = input.ReadString();
            break;
          }
          case 58: {
            Gearbox = input.ReadString();
            break;
          }
          case 66: {
            Color = input.ReadString();
            break;
          }
          case 74: {
            Description = input.ReadString();
            break;
          }
          case 80: {
            PricePerDay = input.ReadInt32();
            break;
          }
          case 88: {
            Status = (global::CarRentalData.CarStatus) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
