// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public final class Car {
  private Car() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto.CarStatus}
   */
  public enum CarStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AVAILABLE = 0;</code>
     */
    AVAILABLE(0),
    /**
     * <code>RESERVED = 1;</code>
     */
    RESERVED(1),
    /**
     * <code>UNAVAILABLE = 2;</code>
     */
    UNAVAILABLE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>AVAILABLE = 0;</code>
     */
    public static final int AVAILABLE_VALUE = 0;
    /**
     * <code>RESERVED = 1;</code>
     */
    public static final int RESERVED_VALUE = 1;
    /**
     * <code>UNAVAILABLE = 2;</code>
     */
    public static final int UNAVAILABLE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CarStatus valueOf(int value) {
      return forNumber(value);
    }

    public static CarStatus forNumber(int value) {
      switch (value) {
        case 0: return AVAILABLE;
        case 1: return RESERVED;
        case 2: return UNAVAILABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CarStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CarStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CarStatus>() {
            public CarStatus findValueByNumber(int number) {
              return CarStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.Car.getDescriptor().getEnumTypes().get(0);
    }

    private static final CarStatus[] VALUES = values();

    public static CarStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CarStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.CarStatus)
  }

  public interface CarProtoObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.CarProtoObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 Id = 1;</code>
     */
    int getId();

    /**
     * <code>string Brand = 2;</code>
     */
    java.lang.String getBrand();
    /**
     * <code>string Brand = 2;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string Model = 3;</code>
     */
    java.lang.String getModel();
    /**
     * <code>string Model = 3;</code>
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>string BodyType = 4;</code>
     */
    java.lang.String getBodyType();
    /**
     * <code>string BodyType = 4;</code>
     */
    com.google.protobuf.ByteString
        getBodyTypeBytes();

    /**
     * <code>int32 HorsePower = 5;</code>
     */
    int getHorsePower();

    /**
     * <code>string FuelType = 6;</code>
     */
    java.lang.String getFuelType();
    /**
     * <code>string FuelType = 6;</code>
     */
    com.google.protobuf.ByteString
        getFuelTypeBytes();

    /**
     * <code>string Gearbox = 7;</code>
     */
    java.lang.String getGearbox();
    /**
     * <code>string Gearbox = 7;</code>
     */
    com.google.protobuf.ByteString
        getGearboxBytes();

    /**
     * <code>string Color = 8;</code>
     */
    java.lang.String getColor();
    /**
     * <code>string Color = 8;</code>
     */
    com.google.protobuf.ByteString
        getColorBytes();

    /**
     * <code>string Description = 9;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string Description = 9;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>int32 PricePerDay = 10;</code>
     */
    int getPricePerDay();

    /**
     * <code>.proto.CarStatus Status = 11;</code>
     */
    int getStatusValue();
    /**
     * <code>.proto.CarStatus Status = 11;</code>
     */
    proto.Car.CarStatus getStatus();
  }
  /**
   * Protobuf type {@code proto.CarProtoObj}
   */
  public  static final class CarProtoObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.CarProtoObj)
      CarProtoObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CarProtoObj.newBuilder() to construct.
    private CarProtoObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CarProtoObj() {
      id_ = 0;
      brand_ = "";
      model_ = "";
      bodyType_ = "";
      horsePower_ = 0;
      fuelType_ = "";
      gearbox_ = "";
      color_ = "";
      description_ = "";
      pricePerDay_ = 0;
      status_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CarProtoObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              model_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              bodyType_ = s;
              break;
            }
            case 40: {

              horsePower_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              fuelType_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              gearbox_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              color_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 80: {

              pricePerDay_ = input.readInt32();
              break;
            }
            case 88: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Car.internal_static_proto_CarProtoObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Car.internal_static_proto_CarProtoObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Car.CarProtoObj.class, proto.Car.CarProtoObj.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 Id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int BRAND_FIELD_NUMBER = 2;
    private volatile java.lang.Object brand_;
    /**
     * <code>string Brand = 2;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string Brand = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODEL_FIELD_NUMBER = 3;
    private volatile java.lang.Object model_;
    /**
     * <code>string Model = 3;</code>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      }
    }
    /**
     * <code>string Model = 3;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODYTYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object bodyType_;
    /**
     * <code>string BodyType = 4;</code>
     */
    public java.lang.String getBodyType() {
      java.lang.Object ref = bodyType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bodyType_ = s;
        return s;
      }
    }
    /**
     * <code>string BodyType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBodyTypeBytes() {
      java.lang.Object ref = bodyType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bodyType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HORSEPOWER_FIELD_NUMBER = 5;
    private int horsePower_;
    /**
     * <code>int32 HorsePower = 5;</code>
     */
    public int getHorsePower() {
      return horsePower_;
    }

    public static final int FUELTYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object fuelType_;
    /**
     * <code>string FuelType = 6;</code>
     */
    public java.lang.String getFuelType() {
      java.lang.Object ref = fuelType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fuelType_ = s;
        return s;
      }
    }
    /**
     * <code>string FuelType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFuelTypeBytes() {
      java.lang.Object ref = fuelType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fuelType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GEARBOX_FIELD_NUMBER = 7;
    private volatile java.lang.Object gearbox_;
    /**
     * <code>string Gearbox = 7;</code>
     */
    public java.lang.String getGearbox() {
      java.lang.Object ref = gearbox_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gearbox_ = s;
        return s;
      }
    }
    /**
     * <code>string Gearbox = 7;</code>
     */
    public com.google.protobuf.ByteString
        getGearboxBytes() {
      java.lang.Object ref = gearbox_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gearbox_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOR_FIELD_NUMBER = 8;
    private volatile java.lang.Object color_;
    /**
     * <code>string Color = 8;</code>
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        color_ = s;
        return s;
      }
    }
    /**
     * <code>string Color = 8;</code>
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 9;
    private volatile java.lang.Object description_;
    /**
     * <code>string Description = 9;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string Description = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICEPERDAY_FIELD_NUMBER = 10;
    private int pricePerDay_;
    /**
     * <code>int32 PricePerDay = 10;</code>
     */
    public int getPricePerDay() {
      return pricePerDay_;
    }

    public static final int STATUS_FIELD_NUMBER = 11;
    private int status_;
    /**
     * <code>.proto.CarStatus Status = 11;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.proto.CarStatus Status = 11;</code>
     */
    public proto.Car.CarStatus getStatus() {
      @SuppressWarnings("deprecation")
      proto.Car.CarStatus result = proto.Car.CarStatus.valueOf(status_);
      return result == null ? proto.Car.CarStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, brand_);
      }
      if (!getModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, model_);
      }
      if (!getBodyTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, bodyType_);
      }
      if (horsePower_ != 0) {
        output.writeInt32(5, horsePower_);
      }
      if (!getFuelTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, fuelType_);
      }
      if (!getGearboxBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, gearbox_);
      }
      if (!getColorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, color_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, description_);
      }
      if (pricePerDay_ != 0) {
        output.writeInt32(10, pricePerDay_);
      }
      if (status_ != proto.Car.CarStatus.AVAILABLE.getNumber()) {
        output.writeEnum(11, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, brand_);
      }
      if (!getModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, model_);
      }
      if (!getBodyTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, bodyType_);
      }
      if (horsePower_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, horsePower_);
      }
      if (!getFuelTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, fuelType_);
      }
      if (!getGearboxBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, gearbox_);
      }
      if (!getColorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, color_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, description_);
      }
      if (pricePerDay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, pricePerDay_);
      }
      if (status_ != proto.Car.CarStatus.AVAILABLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Car.CarProtoObj)) {
        return super.equals(obj);
      }
      proto.Car.CarProtoObj other = (proto.Car.CarProtoObj) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getBrand()
          .equals(other.getBrand());
      result = result && getModel()
          .equals(other.getModel());
      result = result && getBodyType()
          .equals(other.getBodyType());
      result = result && (getHorsePower()
          == other.getHorsePower());
      result = result && getFuelType()
          .equals(other.getFuelType());
      result = result && getGearbox()
          .equals(other.getGearbox());
      result = result && getColor()
          .equals(other.getColor());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && (getPricePerDay()
          == other.getPricePerDay());
      result = result && status_ == other.status_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
      hash = (37 * hash) + BODYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBodyType().hashCode();
      hash = (37 * hash) + HORSEPOWER_FIELD_NUMBER;
      hash = (53 * hash) + getHorsePower();
      hash = (37 * hash) + FUELTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFuelType().hashCode();
      hash = (37 * hash) + GEARBOX_FIELD_NUMBER;
      hash = (53 * hash) + getGearbox().hashCode();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + PRICEPERDAY_FIELD_NUMBER;
      hash = (53 * hash) + getPricePerDay();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Car.CarProtoObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Car.CarProtoObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Car.CarProtoObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Car.CarProtoObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Car.CarProtoObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Car.CarProtoObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Car.CarProtoObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Car.CarProtoObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Car.CarProtoObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Car.CarProtoObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Car.CarProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Car.CarProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Car.CarProtoObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.CarProtoObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.CarProtoObj)
        proto.Car.CarProtoObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Car.internal_static_proto_CarProtoObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Car.internal_static_proto_CarProtoObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Car.CarProtoObj.class, proto.Car.CarProtoObj.Builder.class);
      }

      // Construct using proto.Car.CarProtoObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        brand_ = "";

        model_ = "";

        bodyType_ = "";

        horsePower_ = 0;

        fuelType_ = "";

        gearbox_ = "";

        color_ = "";

        description_ = "";

        pricePerDay_ = 0;

        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Car.internal_static_proto_CarProtoObj_descriptor;
      }

      @java.lang.Override
      public proto.Car.CarProtoObj getDefaultInstanceForType() {
        return proto.Car.CarProtoObj.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Car.CarProtoObj build() {
        proto.Car.CarProtoObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Car.CarProtoObj buildPartial() {
        proto.Car.CarProtoObj result = new proto.Car.CarProtoObj(this);
        result.id_ = id_;
        result.brand_ = brand_;
        result.model_ = model_;
        result.bodyType_ = bodyType_;
        result.horsePower_ = horsePower_;
        result.fuelType_ = fuelType_;
        result.gearbox_ = gearbox_;
        result.color_ = color_;
        result.description_ = description_;
        result.pricePerDay_ = pricePerDay_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Car.CarProtoObj) {
          return mergeFrom((proto.Car.CarProtoObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Car.CarProtoObj other) {
        if (other == proto.Car.CarProtoObj.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getModel().isEmpty()) {
          model_ = other.model_;
          onChanged();
        }
        if (!other.getBodyType().isEmpty()) {
          bodyType_ = other.bodyType_;
          onChanged();
        }
        if (other.getHorsePower() != 0) {
          setHorsePower(other.getHorsePower());
        }
        if (!other.getFuelType().isEmpty()) {
          fuelType_ = other.fuelType_;
          onChanged();
        }
        if (!other.getGearbox().isEmpty()) {
          gearbox_ = other.gearbox_;
          onChanged();
        }
        if (!other.getColor().isEmpty()) {
          color_ = other.color_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getPricePerDay() != 0) {
          setPricePerDay(other.getPricePerDay());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Car.CarProtoObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Car.CarProtoObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 Id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 Id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object brand_ = "";
      /**
       * <code>string Brand = 2;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Brand = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Brand = 2;</code>
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Brand = 2;</code>
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string Brand = 2;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <code>string Model = 3;</code>
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Model = 3;</code>
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Model = 3;</code>
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Model = 3;</code>
       */
      public Builder clearModel() {
        
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      /**
       * <code>string Model = 3;</code>
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        model_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bodyType_ = "";
      /**
       * <code>string BodyType = 4;</code>
       */
      public java.lang.String getBodyType() {
        java.lang.Object ref = bodyType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bodyType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string BodyType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBodyTypeBytes() {
        java.lang.Object ref = bodyType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bodyType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string BodyType = 4;</code>
       */
      public Builder setBodyType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bodyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string BodyType = 4;</code>
       */
      public Builder clearBodyType() {
        
        bodyType_ = getDefaultInstance().getBodyType();
        onChanged();
        return this;
      }
      /**
       * <code>string BodyType = 4;</code>
       */
      public Builder setBodyTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bodyType_ = value;
        onChanged();
        return this;
      }

      private int horsePower_ ;
      /**
       * <code>int32 HorsePower = 5;</code>
       */
      public int getHorsePower() {
        return horsePower_;
      }
      /**
       * <code>int32 HorsePower = 5;</code>
       */
      public Builder setHorsePower(int value) {
        
        horsePower_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 HorsePower = 5;</code>
       */
      public Builder clearHorsePower() {
        
        horsePower_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fuelType_ = "";
      /**
       * <code>string FuelType = 6;</code>
       */
      public java.lang.String getFuelType() {
        java.lang.Object ref = fuelType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fuelType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string FuelType = 6;</code>
       */
      public com.google.protobuf.ByteString
          getFuelTypeBytes() {
        java.lang.Object ref = fuelType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fuelType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string FuelType = 6;</code>
       */
      public Builder setFuelType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fuelType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string FuelType = 6;</code>
       */
      public Builder clearFuelType() {
        
        fuelType_ = getDefaultInstance().getFuelType();
        onChanged();
        return this;
      }
      /**
       * <code>string FuelType = 6;</code>
       */
      public Builder setFuelTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fuelType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gearbox_ = "";
      /**
       * <code>string Gearbox = 7;</code>
       */
      public java.lang.String getGearbox() {
        java.lang.Object ref = gearbox_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gearbox_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Gearbox = 7;</code>
       */
      public com.google.protobuf.ByteString
          getGearboxBytes() {
        java.lang.Object ref = gearbox_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gearbox_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Gearbox = 7;</code>
       */
      public Builder setGearbox(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gearbox_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Gearbox = 7;</code>
       */
      public Builder clearGearbox() {
        
        gearbox_ = getDefaultInstance().getGearbox();
        onChanged();
        return this;
      }
      /**
       * <code>string Gearbox = 7;</code>
       */
      public Builder setGearboxBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gearbox_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object color_ = "";
      /**
       * <code>string Color = 8;</code>
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          color_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Color = 8;</code>
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Color = 8;</code>
       */
      public Builder setColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Color = 8;</code>
       */
      public Builder clearColor() {
        
        color_ = getDefaultInstance().getColor();
        onChanged();
        return this;
      }
      /**
       * <code>string Color = 8;</code>
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        color_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string Description = 9;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Description = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Description = 9;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Description = 9;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string Description = 9;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int pricePerDay_ ;
      /**
       * <code>int32 PricePerDay = 10;</code>
       */
      public int getPricePerDay() {
        return pricePerDay_;
      }
      /**
       * <code>int32 PricePerDay = 10;</code>
       */
      public Builder setPricePerDay(int value) {
        
        pricePerDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 PricePerDay = 10;</code>
       */
      public Builder clearPricePerDay() {
        
        pricePerDay_ = 0;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.proto.CarStatus Status = 11;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.proto.CarStatus Status = 11;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.CarStatus Status = 11;</code>
       */
      public proto.Car.CarStatus getStatus() {
        @SuppressWarnings("deprecation")
        proto.Car.CarStatus result = proto.Car.CarStatus.valueOf(status_);
        return result == null ? proto.Car.CarStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.CarStatus Status = 11;</code>
       */
      public Builder setStatus(proto.Car.CarStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.CarStatus Status = 11;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.CarProtoObj)
    }

    // @@protoc_insertion_point(class_scope:proto.CarProtoObj)
    private static final proto.Car.CarProtoObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Car.CarProtoObj();
    }

    public static proto.Car.CarProtoObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CarProtoObj>
        PARSER = new com.google.protobuf.AbstractParser<CarProtoObj>() {
      @java.lang.Override
      public CarProtoObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CarProtoObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CarProtoObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CarProtoObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Car.CarProtoObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CarProtoObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CarProtoObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcar.proto\022\005proto\032\036google/protobuf/wrap" +
      "pers.proto\032\033google/protobuf/empty.proto\"" +
      "\333\001\n\013CarProtoObj\022\n\n\002Id\030\001 \001(\005\022\r\n\005Brand\030\002 \001" +
      "(\t\022\r\n\005Model\030\003 \001(\t\022\020\n\010BodyType\030\004 \001(\t\022\022\n\nH" +
      "orsePower\030\005 \001(\005\022\020\n\010FuelType\030\006 \001(\t\022\017\n\007Gea" +
      "rbox\030\007 \001(\t\022\r\n\005Color\030\010 \001(\t\022\023\n\013Description" +
      "\030\t \001(\t\022\023\n\013PricePerDay\030\n \001(\005\022 \n\006Status\030\013 " +
      "\001(\0162\020.proto.CarStatus*9\n\tCarStatus\022\r\n\tAV" +
      "AILABLE\020\000\022\014\n\010RESERVED\020\001\022\017\n\013UNAVAILABLE\020\002" +
      "2H\n\017CarProtoService\0225\n\tCreateCar\022\022.proto" +
      ".CarProtoObj\032\022.proto.CarProtoObj\"\000b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_proto_CarProtoObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_CarProtoObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CarProtoObj_descriptor,
        new java.lang.String[] { "Id", "Brand", "Model", "BodyType", "HorsePower", "FuelType", "Gearbox", "Color", "Description", "PricePerDay", "Status", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
