// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package proto;

public final class Reservation {
  private Reservation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReservationProtoObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ReservationProtoObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 Id = 1;</code>
     */
    int getId();

    /**
     * <code>int32 CarId = 2;</code>
     */
    int getCarId();

    /**
     * <code>string UserName = 3;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>string UserName = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>.google.protobuf.Timestamp StartDate = 4;</code>
     */
    boolean hasStartDate();
    /**
     * <code>.google.protobuf.Timestamp StartDate = 4;</code>
     */
    com.google.protobuf.Timestamp getStartDate();
    /**
     * <code>.google.protobuf.Timestamp StartDate = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp EndDate = 5;</code>
     */
    boolean hasEndDate();
    /**
     * <code>.google.protobuf.Timestamp EndDate = 5;</code>
     */
    com.google.protobuf.Timestamp getEndDate();
    /**
     * <code>.google.protobuf.Timestamp EndDate = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder();

    /**
     * <code>double TotalPrice = 6;</code>
     */
    double getTotalPrice();
  }
  /**
   * Protobuf type {@code proto.ReservationProtoObj}
   */
  public  static final class ReservationProtoObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ReservationProtoObj)
      ReservationProtoObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReservationProtoObj.newBuilder() to construct.
    private ReservationProtoObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReservationProtoObj() {
      id_ = 0;
      carId_ = 0;
      userName_ = "";
      totalPrice_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReservationProtoObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              carId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (startDate_ != null) {
                subBuilder = startDate_.toBuilder();
              }
              startDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(startDate_);
                startDate_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (endDate_ != null) {
                subBuilder = endDate_.toBuilder();
              }
              endDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(endDate_);
                endDate_ = subBuilder.buildPartial();
              }

              break;
            }
            case 49: {

              totalPrice_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Reservation.internal_static_proto_ReservationProtoObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Reservation.internal_static_proto_ReservationProtoObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Reservation.ReservationProtoObj.class, proto.Reservation.ReservationProtoObj.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 Id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int CARID_FIELD_NUMBER = 2;
    private int carId_;
    /**
     * <code>int32 CarId = 2;</code>
     */
    public int getCarId() {
      return carId_;
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object userName_;
    /**
     * <code>string UserName = 3;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string UserName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTDATE_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp startDate_;
    /**
     * <code>.google.protobuf.Timestamp StartDate = 4;</code>
     */
    public boolean hasStartDate() {
      return startDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp StartDate = 4;</code>
     */
    public com.google.protobuf.Timestamp getStartDate() {
      return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
    }
    /**
     * <code>.google.protobuf.Timestamp StartDate = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
      return getStartDate();
    }

    public static final int ENDDATE_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp endDate_;
    /**
     * <code>.google.protobuf.Timestamp EndDate = 5;</code>
     */
    public boolean hasEndDate() {
      return endDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp EndDate = 5;</code>
     */
    public com.google.protobuf.Timestamp getEndDate() {
      return endDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
    }
    /**
     * <code>.google.protobuf.Timestamp EndDate = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder() {
      return getEndDate();
    }

    public static final int TOTALPRICE_FIELD_NUMBER = 6;
    private double totalPrice_;
    /**
     * <code>double TotalPrice = 6;</code>
     */
    public double getTotalPrice() {
      return totalPrice_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (carId_ != 0) {
        output.writeInt32(2, carId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userName_);
      }
      if (startDate_ != null) {
        output.writeMessage(4, getStartDate());
      }
      if (endDate_ != null) {
        output.writeMessage(5, getEndDate());
      }
      if (totalPrice_ != 0D) {
        output.writeDouble(6, totalPrice_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (carId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, carId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userName_);
      }
      if (startDate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getStartDate());
      }
      if (endDate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getEndDate());
      }
      if (totalPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, totalPrice_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Reservation.ReservationProtoObj)) {
        return super.equals(obj);
      }
      proto.Reservation.ReservationProtoObj other = (proto.Reservation.ReservationProtoObj) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getCarId()
          == other.getCarId());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && (hasStartDate() == other.hasStartDate());
      if (hasStartDate()) {
        result = result && getStartDate()
            .equals(other.getStartDate());
      }
      result = result && (hasEndDate() == other.hasEndDate());
      if (hasEndDate()) {
        result = result && getEndDate()
            .equals(other.getEndDate());
      }
      result = result && (
          java.lang.Double.doubleToLongBits(getTotalPrice())
          == java.lang.Double.doubleToLongBits(
              other.getTotalPrice()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + CARID_FIELD_NUMBER;
      hash = (53 * hash) + getCarId();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      if (hasStartDate()) {
        hash = (37 * hash) + STARTDATE_FIELD_NUMBER;
        hash = (53 * hash) + getStartDate().hashCode();
      }
      if (hasEndDate()) {
        hash = (37 * hash) + ENDDATE_FIELD_NUMBER;
        hash = (53 * hash) + getEndDate().hashCode();
      }
      hash = (37 * hash) + TOTALPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTotalPrice()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Reservation.ReservationProtoObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Reservation.ReservationProtoObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Reservation.ReservationProtoObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Reservation.ReservationProtoObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Reservation.ReservationProtoObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Reservation.ReservationProtoObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Reservation.ReservationProtoObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Reservation.ReservationProtoObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Reservation.ReservationProtoObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Reservation.ReservationProtoObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Reservation.ReservationProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Reservation.ReservationProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Reservation.ReservationProtoObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ReservationProtoObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ReservationProtoObj)
        proto.Reservation.ReservationProtoObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Reservation.internal_static_proto_ReservationProtoObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Reservation.internal_static_proto_ReservationProtoObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Reservation.ReservationProtoObj.class, proto.Reservation.ReservationProtoObj.Builder.class);
      }

      // Construct using proto.Reservation.ReservationProtoObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        carId_ = 0;

        userName_ = "";

        if (startDateBuilder_ == null) {
          startDate_ = null;
        } else {
          startDate_ = null;
          startDateBuilder_ = null;
        }
        if (endDateBuilder_ == null) {
          endDate_ = null;
        } else {
          endDate_ = null;
          endDateBuilder_ = null;
        }
        totalPrice_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Reservation.internal_static_proto_ReservationProtoObj_descriptor;
      }

      @java.lang.Override
      public proto.Reservation.ReservationProtoObj getDefaultInstanceForType() {
        return proto.Reservation.ReservationProtoObj.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Reservation.ReservationProtoObj build() {
        proto.Reservation.ReservationProtoObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Reservation.ReservationProtoObj buildPartial() {
        proto.Reservation.ReservationProtoObj result = new proto.Reservation.ReservationProtoObj(this);
        result.id_ = id_;
        result.carId_ = carId_;
        result.userName_ = userName_;
        if (startDateBuilder_ == null) {
          result.startDate_ = startDate_;
        } else {
          result.startDate_ = startDateBuilder_.build();
        }
        if (endDateBuilder_ == null) {
          result.endDate_ = endDate_;
        } else {
          result.endDate_ = endDateBuilder_.build();
        }
        result.totalPrice_ = totalPrice_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Reservation.ReservationProtoObj) {
          return mergeFrom((proto.Reservation.ReservationProtoObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Reservation.ReservationProtoObj other) {
        if (other == proto.Reservation.ReservationProtoObj.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getCarId() != 0) {
          setCarId(other.getCarId());
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasStartDate()) {
          mergeStartDate(other.getStartDate());
        }
        if (other.hasEndDate()) {
          mergeEndDate(other.getEndDate());
        }
        if (other.getTotalPrice() != 0D) {
          setTotalPrice(other.getTotalPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Reservation.ReservationProtoObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Reservation.ReservationProtoObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 Id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 Id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int carId_ ;
      /**
       * <code>int32 CarId = 2;</code>
       */
      public int getCarId() {
        return carId_;
      }
      /**
       * <code>int32 CarId = 2;</code>
       */
      public Builder setCarId(int value) {
        
        carId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 CarId = 2;</code>
       */
      public Builder clearCarId() {
        
        carId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string UserName = 3;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string UserName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string UserName = 3;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string UserName = 3;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string UserName = 3;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp startDate_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startDateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp StartDate = 4;</code>
       */
      public boolean hasStartDate() {
        return startDateBuilder_ != null || startDate_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp StartDate = 4;</code>
       */
      public com.google.protobuf.Timestamp getStartDate() {
        if (startDateBuilder_ == null) {
          return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
        } else {
          return startDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp StartDate = 4;</code>
       */
      public Builder setStartDate(com.google.protobuf.Timestamp value) {
        if (startDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          startDate_ = value;
          onChanged();
        } else {
          startDateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp StartDate = 4;</code>
       */
      public Builder setStartDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (startDateBuilder_ == null) {
          startDate_ = builderForValue.build();
          onChanged();
        } else {
          startDateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp StartDate = 4;</code>
       */
      public Builder mergeStartDate(com.google.protobuf.Timestamp value) {
        if (startDateBuilder_ == null) {
          if (startDate_ != null) {
            startDate_ =
              com.google.protobuf.Timestamp.newBuilder(startDate_).mergeFrom(value).buildPartial();
          } else {
            startDate_ = value;
          }
          onChanged();
        } else {
          startDateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp StartDate = 4;</code>
       */
      public Builder clearStartDate() {
        if (startDateBuilder_ == null) {
          startDate_ = null;
          onChanged();
        } else {
          startDate_ = null;
          startDateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp StartDate = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getStartDateBuilder() {
        
        onChanged();
        return getStartDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp StartDate = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
        if (startDateBuilder_ != null) {
          return startDateBuilder_.getMessageOrBuilder();
        } else {
          return startDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp StartDate = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getStartDateFieldBuilder() {
        if (startDateBuilder_ == null) {
          startDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getStartDate(),
                  getParentForChildren(),
                  isClean());
          startDate_ = null;
        }
        return startDateBuilder_;
      }

      private com.google.protobuf.Timestamp endDate_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> endDateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp EndDate = 5;</code>
       */
      public boolean hasEndDate() {
        return endDateBuilder_ != null || endDate_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp EndDate = 5;</code>
       */
      public com.google.protobuf.Timestamp getEndDate() {
        if (endDateBuilder_ == null) {
          return endDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
        } else {
          return endDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp EndDate = 5;</code>
       */
      public Builder setEndDate(com.google.protobuf.Timestamp value) {
        if (endDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          endDate_ = value;
          onChanged();
        } else {
          endDateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp EndDate = 5;</code>
       */
      public Builder setEndDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (endDateBuilder_ == null) {
          endDate_ = builderForValue.build();
          onChanged();
        } else {
          endDateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp EndDate = 5;</code>
       */
      public Builder mergeEndDate(com.google.protobuf.Timestamp value) {
        if (endDateBuilder_ == null) {
          if (endDate_ != null) {
            endDate_ =
              com.google.protobuf.Timestamp.newBuilder(endDate_).mergeFrom(value).buildPartial();
          } else {
            endDate_ = value;
          }
          onChanged();
        } else {
          endDateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp EndDate = 5;</code>
       */
      public Builder clearEndDate() {
        if (endDateBuilder_ == null) {
          endDate_ = null;
          onChanged();
        } else {
          endDate_ = null;
          endDateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp EndDate = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getEndDateBuilder() {
        
        onChanged();
        return getEndDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp EndDate = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder() {
        if (endDateBuilder_ != null) {
          return endDateBuilder_.getMessageOrBuilder();
        } else {
          return endDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp EndDate = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getEndDateFieldBuilder() {
        if (endDateBuilder_ == null) {
          endDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getEndDate(),
                  getParentForChildren(),
                  isClean());
          endDate_ = null;
        }
        return endDateBuilder_;
      }

      private double totalPrice_ ;
      /**
       * <code>double TotalPrice = 6;</code>
       */
      public double getTotalPrice() {
        return totalPrice_;
      }
      /**
       * <code>double TotalPrice = 6;</code>
       */
      public Builder setTotalPrice(double value) {
        
        totalPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double TotalPrice = 6;</code>
       */
      public Builder clearTotalPrice() {
        
        totalPrice_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ReservationProtoObj)
    }

    // @@protoc_insertion_point(class_scope:proto.ReservationProtoObj)
    private static final proto.Reservation.ReservationProtoObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Reservation.ReservationProtoObj();
    }

    public static proto.Reservation.ReservationProtoObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReservationProtoObj>
        PARSER = new com.google.protobuf.AbstractParser<ReservationProtoObj>() {
      @java.lang.Override
      public ReservationProtoObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReservationProtoObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReservationProtoObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReservationProtoObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Reservation.ReservationProtoObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReservationProtoListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ReservationProtoList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
     */
    java.util.List<proto.Reservation.ReservationProtoObj> 
        getReservationList();
    /**
     * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
     */
    proto.Reservation.ReservationProtoObj getReservation(int index);
    /**
     * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
     */
    int getReservationCount();
    /**
     * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
     */
    java.util.List<? extends proto.Reservation.ReservationProtoObjOrBuilder> 
        getReservationOrBuilderList();
    /**
     * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
     */
    proto.Reservation.ReservationProtoObjOrBuilder getReservationOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.ReservationProtoList}
   */
  public  static final class ReservationProtoList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ReservationProtoList)
      ReservationProtoListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReservationProtoList.newBuilder() to construct.
    private ReservationProtoList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReservationProtoList() {
      reservation_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReservationProtoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                reservation_ = new java.util.ArrayList<proto.Reservation.ReservationProtoObj>();
                mutable_bitField0_ |= 0x00000001;
              }
              reservation_.add(
                  input.readMessage(proto.Reservation.ReservationProtoObj.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          reservation_ = java.util.Collections.unmodifiableList(reservation_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Reservation.internal_static_proto_ReservationProtoList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Reservation.internal_static_proto_ReservationProtoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Reservation.ReservationProtoList.class, proto.Reservation.ReservationProtoList.Builder.class);
    }

    public static final int RESERVATION_FIELD_NUMBER = 1;
    private java.util.List<proto.Reservation.ReservationProtoObj> reservation_;
    /**
     * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
     */
    public java.util.List<proto.Reservation.ReservationProtoObj> getReservationList() {
      return reservation_;
    }
    /**
     * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
     */
    public java.util.List<? extends proto.Reservation.ReservationProtoObjOrBuilder> 
        getReservationOrBuilderList() {
      return reservation_;
    }
    /**
     * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
     */
    public int getReservationCount() {
      return reservation_.size();
    }
    /**
     * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
     */
    public proto.Reservation.ReservationProtoObj getReservation(int index) {
      return reservation_.get(index);
    }
    /**
     * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
     */
    public proto.Reservation.ReservationProtoObjOrBuilder getReservationOrBuilder(
        int index) {
      return reservation_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < reservation_.size(); i++) {
        output.writeMessage(1, reservation_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < reservation_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, reservation_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Reservation.ReservationProtoList)) {
        return super.equals(obj);
      }
      proto.Reservation.ReservationProtoList other = (proto.Reservation.ReservationProtoList) obj;

      boolean result = true;
      result = result && getReservationList()
          .equals(other.getReservationList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getReservationCount() > 0) {
        hash = (37 * hash) + RESERVATION_FIELD_NUMBER;
        hash = (53 * hash) + getReservationList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Reservation.ReservationProtoList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Reservation.ReservationProtoList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Reservation.ReservationProtoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Reservation.ReservationProtoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Reservation.ReservationProtoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Reservation.ReservationProtoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Reservation.ReservationProtoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Reservation.ReservationProtoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Reservation.ReservationProtoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Reservation.ReservationProtoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Reservation.ReservationProtoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Reservation.ReservationProtoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Reservation.ReservationProtoList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ReservationProtoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ReservationProtoList)
        proto.Reservation.ReservationProtoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Reservation.internal_static_proto_ReservationProtoList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Reservation.internal_static_proto_ReservationProtoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Reservation.ReservationProtoList.class, proto.Reservation.ReservationProtoList.Builder.class);
      }

      // Construct using proto.Reservation.ReservationProtoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getReservationFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (reservationBuilder_ == null) {
          reservation_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          reservationBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Reservation.internal_static_proto_ReservationProtoList_descriptor;
      }

      @java.lang.Override
      public proto.Reservation.ReservationProtoList getDefaultInstanceForType() {
        return proto.Reservation.ReservationProtoList.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Reservation.ReservationProtoList build() {
        proto.Reservation.ReservationProtoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Reservation.ReservationProtoList buildPartial() {
        proto.Reservation.ReservationProtoList result = new proto.Reservation.ReservationProtoList(this);
        int from_bitField0_ = bitField0_;
        if (reservationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            reservation_ = java.util.Collections.unmodifiableList(reservation_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.reservation_ = reservation_;
        } else {
          result.reservation_ = reservationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Reservation.ReservationProtoList) {
          return mergeFrom((proto.Reservation.ReservationProtoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Reservation.ReservationProtoList other) {
        if (other == proto.Reservation.ReservationProtoList.getDefaultInstance()) return this;
        if (reservationBuilder_ == null) {
          if (!other.reservation_.isEmpty()) {
            if (reservation_.isEmpty()) {
              reservation_ = other.reservation_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureReservationIsMutable();
              reservation_.addAll(other.reservation_);
            }
            onChanged();
          }
        } else {
          if (!other.reservation_.isEmpty()) {
            if (reservationBuilder_.isEmpty()) {
              reservationBuilder_.dispose();
              reservationBuilder_ = null;
              reservation_ = other.reservation_;
              bitField0_ = (bitField0_ & ~0x00000001);
              reservationBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getReservationFieldBuilder() : null;
            } else {
              reservationBuilder_.addAllMessages(other.reservation_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Reservation.ReservationProtoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Reservation.ReservationProtoList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.Reservation.ReservationProtoObj> reservation_ =
        java.util.Collections.emptyList();
      private void ensureReservationIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          reservation_ = new java.util.ArrayList<proto.Reservation.ReservationProtoObj>(reservation_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Reservation.ReservationProtoObj, proto.Reservation.ReservationProtoObj.Builder, proto.Reservation.ReservationProtoObjOrBuilder> reservationBuilder_;

      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public java.util.List<proto.Reservation.ReservationProtoObj> getReservationList() {
        if (reservationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reservation_);
        } else {
          return reservationBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public int getReservationCount() {
        if (reservationBuilder_ == null) {
          return reservation_.size();
        } else {
          return reservationBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public proto.Reservation.ReservationProtoObj getReservation(int index) {
        if (reservationBuilder_ == null) {
          return reservation_.get(index);
        } else {
          return reservationBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public Builder setReservation(
          int index, proto.Reservation.ReservationProtoObj value) {
        if (reservationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReservationIsMutable();
          reservation_.set(index, value);
          onChanged();
        } else {
          reservationBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public Builder setReservation(
          int index, proto.Reservation.ReservationProtoObj.Builder builderForValue) {
        if (reservationBuilder_ == null) {
          ensureReservationIsMutable();
          reservation_.set(index, builderForValue.build());
          onChanged();
        } else {
          reservationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public Builder addReservation(proto.Reservation.ReservationProtoObj value) {
        if (reservationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReservationIsMutable();
          reservation_.add(value);
          onChanged();
        } else {
          reservationBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public Builder addReservation(
          int index, proto.Reservation.ReservationProtoObj value) {
        if (reservationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReservationIsMutable();
          reservation_.add(index, value);
          onChanged();
        } else {
          reservationBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public Builder addReservation(
          proto.Reservation.ReservationProtoObj.Builder builderForValue) {
        if (reservationBuilder_ == null) {
          ensureReservationIsMutable();
          reservation_.add(builderForValue.build());
          onChanged();
        } else {
          reservationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public Builder addReservation(
          int index, proto.Reservation.ReservationProtoObj.Builder builderForValue) {
        if (reservationBuilder_ == null) {
          ensureReservationIsMutable();
          reservation_.add(index, builderForValue.build());
          onChanged();
        } else {
          reservationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public Builder addAllReservation(
          java.lang.Iterable<? extends proto.Reservation.ReservationProtoObj> values) {
        if (reservationBuilder_ == null) {
          ensureReservationIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, reservation_);
          onChanged();
        } else {
          reservationBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public Builder clearReservation() {
        if (reservationBuilder_ == null) {
          reservation_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          reservationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public Builder removeReservation(int index) {
        if (reservationBuilder_ == null) {
          ensureReservationIsMutable();
          reservation_.remove(index);
          onChanged();
        } else {
          reservationBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public proto.Reservation.ReservationProtoObj.Builder getReservationBuilder(
          int index) {
        return getReservationFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public proto.Reservation.ReservationProtoObjOrBuilder getReservationOrBuilder(
          int index) {
        if (reservationBuilder_ == null) {
          return reservation_.get(index);  } else {
          return reservationBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public java.util.List<? extends proto.Reservation.ReservationProtoObjOrBuilder> 
           getReservationOrBuilderList() {
        if (reservationBuilder_ != null) {
          return reservationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reservation_);
        }
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public proto.Reservation.ReservationProtoObj.Builder addReservationBuilder() {
        return getReservationFieldBuilder().addBuilder(
            proto.Reservation.ReservationProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public proto.Reservation.ReservationProtoObj.Builder addReservationBuilder(
          int index) {
        return getReservationFieldBuilder().addBuilder(
            index, proto.Reservation.ReservationProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ReservationProtoObj Reservation = 1;</code>
       */
      public java.util.List<proto.Reservation.ReservationProtoObj.Builder> 
           getReservationBuilderList() {
        return getReservationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Reservation.ReservationProtoObj, proto.Reservation.ReservationProtoObj.Builder, proto.Reservation.ReservationProtoObjOrBuilder> 
          getReservationFieldBuilder() {
        if (reservationBuilder_ == null) {
          reservationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.Reservation.ReservationProtoObj, proto.Reservation.ReservationProtoObj.Builder, proto.Reservation.ReservationProtoObjOrBuilder>(
                  reservation_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          reservation_ = null;
        }
        return reservationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ReservationProtoList)
    }

    // @@protoc_insertion_point(class_scope:proto.ReservationProtoList)
    private static final proto.Reservation.ReservationProtoList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Reservation.ReservationProtoList();
    }

    public static proto.Reservation.ReservationProtoList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReservationProtoList>
        PARSER = new com.google.protobuf.AbstractParser<ReservationProtoList>() {
      @java.lang.Override
      public ReservationProtoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReservationProtoList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReservationProtoList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReservationProtoList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Reservation.ReservationProtoList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReservationProtoObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReservationProtoObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReservationProtoList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReservationProtoList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\022\005proto\032\036google/proto" +
      "buf/wrappers.proto\032\033google/protobuf/empt" +
      "y.proto\032\037google/protobuf/timestamp.proto" +
      "\"\262\001\n\023ReservationProtoObj\022\n\n\002Id\030\001 \001(\005\022\r\n\005" +
      "CarId\030\002 \001(\005\022\020\n\010UserName\030\003 \001(\t\022-\n\tStartDa" +
      "te\030\004 \001(\0132\032.google.protobuf.Timestamp\022+\n\007" +
      "EndDate\030\005 \001(\0132\032.google.protobuf.Timestam" +
      "p\022\022\n\nTotalPrice\030\006 \001(\001\"G\n\024ReservationProt" +
      "oList\022/\n\013Reservation\030\001 \003(\0132\032.proto.Reser" +
      "vationProtoObj2\310\004\n\027ReservationProtoServi" +
      "ce\022K\n\021CreateReservation\022\032.proto.Reservat" +
      "ionProtoObj\032\032.proto.ReservationProtoObj\022" +
      "L\n\021ReturnReservation\022\033.google.protobuf.I" +
      "nt32Value\032\032.proto.ReservationProtoObj\022L\n" +
      "\021CancelReservation\022\033.google.protobuf.Int" +
      "32Value\032\032.proto.ReservationProtoObj\022I\n\022G" +
      "etAllReservations\022\026.google.protobuf.Empt" +
      "y\032\033.proto.ReservationProtoList\022M\n\022GetRes" +
      "ervationById\022\033.google.protobuf.Int32Valu" +
      "e\032\032.proto.ReservationProtoObj\022R\n\026GetRese" +
      "rvationsByCarId\022\033.google.protobuf.Int32V" +
      "alue\032\033.proto.ReservationProtoList\022V\n\031Get" +
      "ReservationsByUserName\022\034.google.protobuf" +
      ".StringValue\032\033.proto.ReservationProtoLis" +
      "tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_proto_ReservationProtoObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ReservationProtoObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReservationProtoObj_descriptor,
        new java.lang.String[] { "Id", "CarId", "UserName", "StartDate", "EndDate", "TotalPrice", });
    internal_static_proto_ReservationProtoList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ReservationProtoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReservationProtoList_descriptor,
        new java.lang.String[] { "Reservation", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
