// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package proto;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserProtoObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserProtoObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string firstName = 1;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string lastName = 2;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string password = 4;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 4;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>int64 cprNumber = 5;</code>
     */
    long getCprNumber();

    /**
     * <code>int64 phoneNumber = 6;</code>
     */
    long getPhoneNumber();

    /**
     * <code>bool isAdmin = 7;</code>
     */
    boolean getIsAdmin();
  }
  /**
   * Protobuf type {@code proto.UserProtoObj}
   */
  public  static final class UserProtoObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.UserProtoObj)
      UserProtoObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserProtoObj.newBuilder() to construct.
    private UserProtoObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserProtoObj() {
      firstName_ = "";
      lastName_ = "";
      email_ = "";
      password_ = "";
      cprNumber_ = 0L;
      phoneNumber_ = 0L;
      isAdmin_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserProtoObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 40: {

              cprNumber_ = input.readInt64();
              break;
            }
            case 48: {

              phoneNumber_ = input.readInt64();
              break;
            }
            case 56: {

              isAdmin_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.User.internal_static_proto_UserProtoObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.User.internal_static_proto_UserProtoObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.User.UserProtoObj.class, proto.User.UserProtoObj.Builder.class);
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string firstName = 1;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string lastName = 2;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 4;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 4;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPRNUMBER_FIELD_NUMBER = 5;
    private long cprNumber_;
    /**
     * <code>int64 cprNumber = 5;</code>
     */
    public long getCprNumber() {
      return cprNumber_;
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 6;
    private long phoneNumber_;
    /**
     * <code>int64 phoneNumber = 6;</code>
     */
    public long getPhoneNumber() {
      return phoneNumber_;
    }

    public static final int ISADMIN_FIELD_NUMBER = 7;
    private boolean isAdmin_;
    /**
     * <code>bool isAdmin = 7;</code>
     */
    public boolean getIsAdmin() {
      return isAdmin_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, password_);
      }
      if (cprNumber_ != 0L) {
        output.writeInt64(5, cprNumber_);
      }
      if (phoneNumber_ != 0L) {
        output.writeInt64(6, phoneNumber_);
      }
      if (isAdmin_ != false) {
        output.writeBool(7, isAdmin_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, password_);
      }
      if (cprNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, cprNumber_);
      }
      if (phoneNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, phoneNumber_);
      }
      if (isAdmin_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isAdmin_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.User.UserProtoObj)) {
        return super.equals(obj);
      }
      proto.User.UserProtoObj other = (proto.User.UserProtoObj) obj;

      boolean result = true;
      result = result && getFirstName()
          .equals(other.getFirstName());
      result = result && getLastName()
          .equals(other.getLastName());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && (getCprNumber()
          == other.getCprNumber());
      result = result && (getPhoneNumber()
          == other.getPhoneNumber());
      result = result && (getIsAdmin()
          == other.getIsAdmin());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + CPRNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCprNumber());
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPhoneNumber());
      hash = (37 * hash) + ISADMIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsAdmin());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.User.UserProtoObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.User.UserProtoObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.User.UserProtoObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.User.UserProtoObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.User.UserProtoObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.User.UserProtoObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.User.UserProtoObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.User.UserProtoObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.User.UserProtoObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.User.UserProtoObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.User.UserProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.User.UserProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.User.UserProtoObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.UserProtoObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserProtoObj)
        proto.User.UserProtoObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.User.internal_static_proto_UserProtoObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.User.internal_static_proto_UserProtoObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.User.UserProtoObj.class, proto.User.UserProtoObj.Builder.class);
      }

      // Construct using proto.User.UserProtoObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        firstName_ = "";

        lastName_ = "";

        email_ = "";

        password_ = "";

        cprNumber_ = 0L;

        phoneNumber_ = 0L;

        isAdmin_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.User.internal_static_proto_UserProtoObj_descriptor;
      }

      @java.lang.Override
      public proto.User.UserProtoObj getDefaultInstanceForType() {
        return proto.User.UserProtoObj.getDefaultInstance();
      }

      @java.lang.Override
      public proto.User.UserProtoObj build() {
        proto.User.UserProtoObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.User.UserProtoObj buildPartial() {
        proto.User.UserProtoObj result = new proto.User.UserProtoObj(this);
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.email_ = email_;
        result.password_ = password_;
        result.cprNumber_ = cprNumber_;
        result.phoneNumber_ = phoneNumber_;
        result.isAdmin_ = isAdmin_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.User.UserProtoObj) {
          return mergeFrom((proto.User.UserProtoObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.User.UserProtoObj other) {
        if (other == proto.User.UserProtoObj.getDefaultInstance()) return this;
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (other.getCprNumber() != 0L) {
          setCprNumber(other.getCprNumber());
        }
        if (other.getPhoneNumber() != 0L) {
          setPhoneNumber(other.getPhoneNumber());
        }
        if (other.getIsAdmin() != false) {
          setIsAdmin(other.getIsAdmin());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.User.UserProtoObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.User.UserProtoObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 1;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 2;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 4;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 4;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 4;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 4;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private long cprNumber_ ;
      /**
       * <code>int64 cprNumber = 5;</code>
       */
      public long getCprNumber() {
        return cprNumber_;
      }
      /**
       * <code>int64 cprNumber = 5;</code>
       */
      public Builder setCprNumber(long value) {
        
        cprNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 cprNumber = 5;</code>
       */
      public Builder clearCprNumber() {
        
        cprNumber_ = 0L;
        onChanged();
        return this;
      }

      private long phoneNumber_ ;
      /**
       * <code>int64 phoneNumber = 6;</code>
       */
      public long getPhoneNumber() {
        return phoneNumber_;
      }
      /**
       * <code>int64 phoneNumber = 6;</code>
       */
      public Builder setPhoneNumber(long value) {
        
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 phoneNumber = 6;</code>
       */
      public Builder clearPhoneNumber() {
        
        phoneNumber_ = 0L;
        onChanged();
        return this;
      }

      private boolean isAdmin_ ;
      /**
       * <code>bool isAdmin = 7;</code>
       */
      public boolean getIsAdmin() {
        return isAdmin_;
      }
      /**
       * <code>bool isAdmin = 7;</code>
       */
      public Builder setIsAdmin(boolean value) {
        
        isAdmin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isAdmin = 7;</code>
       */
      public Builder clearIsAdmin() {
        
        isAdmin_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.UserProtoObj)
    }

    // @@protoc_insertion_point(class_scope:proto.UserProtoObj)
    private static final proto.User.UserProtoObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.User.UserProtoObj();
    }

    public static proto.User.UserProtoObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserProtoObj>
        PARSER = new com.google.protobuf.AbstractParser<UserProtoObj>() {
      @java.lang.Override
      public UserProtoObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserProtoObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserProtoObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserProtoObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.User.UserProtoObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
     */
    java.util.List<proto.User.UserProtoObj> 
        getAllUsersList();
    /**
     * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
     */
    proto.User.UserProtoObj getAllUsers(int index);
    /**
     * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
     */
    int getAllUsersCount();
    /**
     * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
     */
    java.util.List<? extends proto.User.UserProtoObjOrBuilder> 
        getAllUsersOrBuilderList();
    /**
     * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
     */
    proto.User.UserProtoObjOrBuilder getAllUsersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.UserListResponse}
   */
  public  static final class UserListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.UserListResponse)
      UserListResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserListResponse.newBuilder() to construct.
    private UserListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserListResponse() {
      allUsers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                allUsers_ = new java.util.ArrayList<proto.User.UserProtoObj>();
                mutable_bitField0_ |= 0x00000001;
              }
              allUsers_.add(
                  input.readMessage(proto.User.UserProtoObj.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          allUsers_ = java.util.Collections.unmodifiableList(allUsers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.User.internal_static_proto_UserListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.User.internal_static_proto_UserListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.User.UserListResponse.class, proto.User.UserListResponse.Builder.class);
    }

    public static final int ALLUSERS_FIELD_NUMBER = 1;
    private java.util.List<proto.User.UserProtoObj> allUsers_;
    /**
     * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
     */
    public java.util.List<proto.User.UserProtoObj> getAllUsersList() {
      return allUsers_;
    }
    /**
     * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
     */
    public java.util.List<? extends proto.User.UserProtoObjOrBuilder> 
        getAllUsersOrBuilderList() {
      return allUsers_;
    }
    /**
     * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
     */
    public int getAllUsersCount() {
      return allUsers_.size();
    }
    /**
     * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
     */
    public proto.User.UserProtoObj getAllUsers(int index) {
      return allUsers_.get(index);
    }
    /**
     * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
     */
    public proto.User.UserProtoObjOrBuilder getAllUsersOrBuilder(
        int index) {
      return allUsers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < allUsers_.size(); i++) {
        output.writeMessage(1, allUsers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < allUsers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allUsers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.User.UserListResponse)) {
        return super.equals(obj);
      }
      proto.User.UserListResponse other = (proto.User.UserListResponse) obj;

      boolean result = true;
      result = result && getAllUsersList()
          .equals(other.getAllUsersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAllUsersCount() > 0) {
        hash = (37 * hash) + ALLUSERS_FIELD_NUMBER;
        hash = (53 * hash) + getAllUsersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.User.UserListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.User.UserListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.User.UserListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.User.UserListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.User.UserListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.User.UserListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.User.UserListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.User.UserListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.User.UserListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.User.UserListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.User.UserListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.User.UserListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.User.UserListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.UserListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserListResponse)
        proto.User.UserListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.User.internal_static_proto_UserListResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.User.internal_static_proto_UserListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.User.UserListResponse.class, proto.User.UserListResponse.Builder.class);
      }

      // Construct using proto.User.UserListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAllUsersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (allUsersBuilder_ == null) {
          allUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          allUsersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.User.internal_static_proto_UserListResponse_descriptor;
      }

      @java.lang.Override
      public proto.User.UserListResponse getDefaultInstanceForType() {
        return proto.User.UserListResponse.getDefaultInstance();
      }

      @java.lang.Override
      public proto.User.UserListResponse build() {
        proto.User.UserListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.User.UserListResponse buildPartial() {
        proto.User.UserListResponse result = new proto.User.UserListResponse(this);
        int from_bitField0_ = bitField0_;
        if (allUsersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            allUsers_ = java.util.Collections.unmodifiableList(allUsers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.allUsers_ = allUsers_;
        } else {
          result.allUsers_ = allUsersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.User.UserListResponse) {
          return mergeFrom((proto.User.UserListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.User.UserListResponse other) {
        if (other == proto.User.UserListResponse.getDefaultInstance()) return this;
        if (allUsersBuilder_ == null) {
          if (!other.allUsers_.isEmpty()) {
            if (allUsers_.isEmpty()) {
              allUsers_ = other.allUsers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAllUsersIsMutable();
              allUsers_.addAll(other.allUsers_);
            }
            onChanged();
          }
        } else {
          if (!other.allUsers_.isEmpty()) {
            if (allUsersBuilder_.isEmpty()) {
              allUsersBuilder_.dispose();
              allUsersBuilder_ = null;
              allUsers_ = other.allUsers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              allUsersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllUsersFieldBuilder() : null;
            } else {
              allUsersBuilder_.addAllMessages(other.allUsers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.User.UserListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.User.UserListResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.User.UserProtoObj> allUsers_ =
        java.util.Collections.emptyList();
      private void ensureAllUsersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          allUsers_ = new java.util.ArrayList<proto.User.UserProtoObj>(allUsers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.User.UserProtoObj, proto.User.UserProtoObj.Builder, proto.User.UserProtoObjOrBuilder> allUsersBuilder_;

      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public java.util.List<proto.User.UserProtoObj> getAllUsersList() {
        if (allUsersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allUsers_);
        } else {
          return allUsersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public int getAllUsersCount() {
        if (allUsersBuilder_ == null) {
          return allUsers_.size();
        } else {
          return allUsersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public proto.User.UserProtoObj getAllUsers(int index) {
        if (allUsersBuilder_ == null) {
          return allUsers_.get(index);
        } else {
          return allUsersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public Builder setAllUsers(
          int index, proto.User.UserProtoObj value) {
        if (allUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllUsersIsMutable();
          allUsers_.set(index, value);
          onChanged();
        } else {
          allUsersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public Builder setAllUsers(
          int index, proto.User.UserProtoObj.Builder builderForValue) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.set(index, builderForValue.build());
          onChanged();
        } else {
          allUsersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public Builder addAllUsers(proto.User.UserProtoObj value) {
        if (allUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllUsersIsMutable();
          allUsers_.add(value);
          onChanged();
        } else {
          allUsersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public Builder addAllUsers(
          int index, proto.User.UserProtoObj value) {
        if (allUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllUsersIsMutable();
          allUsers_.add(index, value);
          onChanged();
        } else {
          allUsersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public Builder addAllUsers(
          proto.User.UserProtoObj.Builder builderForValue) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.add(builderForValue.build());
          onChanged();
        } else {
          allUsersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public Builder addAllUsers(
          int index, proto.User.UserProtoObj.Builder builderForValue) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.add(index, builderForValue.build());
          onChanged();
        } else {
          allUsersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public Builder addAllAllUsers(
          java.lang.Iterable<? extends proto.User.UserProtoObj> values) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allUsers_);
          onChanged();
        } else {
          allUsersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public Builder clearAllUsers() {
        if (allUsersBuilder_ == null) {
          allUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          allUsersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public Builder removeAllUsers(int index) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.remove(index);
          onChanged();
        } else {
          allUsersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public proto.User.UserProtoObj.Builder getAllUsersBuilder(
          int index) {
        return getAllUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public proto.User.UserProtoObjOrBuilder getAllUsersOrBuilder(
          int index) {
        if (allUsersBuilder_ == null) {
          return allUsers_.get(index);  } else {
          return allUsersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public java.util.List<? extends proto.User.UserProtoObjOrBuilder> 
           getAllUsersOrBuilderList() {
        if (allUsersBuilder_ != null) {
          return allUsersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allUsers_);
        }
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public proto.User.UserProtoObj.Builder addAllUsersBuilder() {
        return getAllUsersFieldBuilder().addBuilder(
            proto.User.UserProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public proto.User.UserProtoObj.Builder addAllUsersBuilder(
          int index) {
        return getAllUsersFieldBuilder().addBuilder(
            index, proto.User.UserProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.UserProtoObj allUsers = 1;</code>
       */
      public java.util.List<proto.User.UserProtoObj.Builder> 
           getAllUsersBuilderList() {
        return getAllUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.User.UserProtoObj, proto.User.UserProtoObj.Builder, proto.User.UserProtoObjOrBuilder> 
          getAllUsersFieldBuilder() {
        if (allUsersBuilder_ == null) {
          allUsersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.User.UserProtoObj, proto.User.UserProtoObj.Builder, proto.User.UserProtoObjOrBuilder>(
                  allUsers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          allUsers_ = null;
        }
        return allUsersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.UserListResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.UserListResponse)
    private static final proto.User.UserListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.User.UserListResponse();
    }

    public static proto.User.UserListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserListResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserListResponse>() {
      @java.lang.Override
      public UserListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserListResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserListResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.User.UserListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserProtoObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UserProtoObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UserListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\005proto\032\036google/protobuf/wra" +
      "ppers.proto\032\033google/protobuf/empty.proto" +
      "\"\215\001\n\014UserProtoObj\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010" +
      "lastName\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\020\n\010passwor" +
      "d\030\004 \001(\t\022\021\n\tcprNumber\030\005 \001(\003\022\023\n\013phoneNumbe" +
      "r\030\006 \001(\003\022\017\n\007isAdmin\030\007 \001(\010\"9\n\020UserListResp" +
      "onse\022%\n\010allUsers\030\001 \003(\0132\023.proto.UserProto" +
      "Obj2\324\001\n\020UserProtoService\0228\n\nCreateUser\022\023" +
      ".proto.UserProtoObj\032\023.proto.UserProtoObj" +
      "\"\000\022@\n\013GetAllUsers\022\026.google.protobuf.Empt" +
      "y\032\027.proto.UserListResponse\"\000\022D\n\016FetchUse" +
      "rByCpr\022\033.google.protobuf.Int64Value\032\023.pr" +
      "oto.UserProtoObj\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_proto_UserProtoObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_UserProtoObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserProtoObj_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "Password", "CprNumber", "PhoneNumber", "IsAdmin", });
    internal_static_proto_UserListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_UserListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UserListResponse_descriptor,
        new java.lang.String[] { "AllUsers", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
